name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before we start, be sure you are aware of the following points:

        * If your issue is specific to a certain plugin, create the issue on that plugin's GitHub project page instead.
        * Avoid duplicating any existing issues which already track or resolve your problem, search the existing issues first.
        * Aim to find a descriptive and precise title for your bug report.
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe The Bug
      description: |
        Pleased provide a clear and concise description of what the bug is. Be sure to include:

        * What is happening?
        * What you expect to happen?
        * Clear steps explaining how to reproduce the problem.
      placeholder: |
        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please provide the relevant logs showing the error that occurred.

        * Keep this short. Do not paste in hundreds of lines repeating the same error.
        * Show the logs from the service being restarted until the error occurs.
    validations:
      required: false
  - type: textarea
    id: json-config
    attributes:
      label: Config
      render: JSON
      description: |
        If relevant to your bug report, please include your Homebridge config (`config.json`).

        * If you're unsure if the config is relevant, please include it.
        * Be sure to **remove any sensitive information (passwords, tokens, etc.).**
    validations:
      required: false
  - type: input
    id: homebridge-ui-version
    attributes:
      label: Homebridge UI Version
    validations:
      required: true
  - type: input
    id: homebridge-version
    attributes:
      label: Homebridge Version
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: |
        We only accept bug reports for systems running even numbered versions of Node.js. See [this link](https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js) for more information.
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      options:
        - Official Homebridge Raspberry Pi Image
        - Raspberry Pi OS / Raspbian
        - Ubuntu / Debian (or a variant)
        - Fedora / CentOS / RedHat (or a variant)
        - macOS
        - Windows 10
        - Windows 11
        - Synology DSM
        - QNAP
        - Unraid
        - Other (specify in description)
      description: |
        If your operating system is not listed, please provide it in the bug description.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Environment Info
      options:
        - Using Docker
        - Using Hyper-V
        - Using hb-service
        - Using systemd
        - Using pm2
        - Other (specify in description)
      description: |
        If your Environment Info is not listed, please provide it in the bug description.
  - type: dropdown
    id: raspberry-pi-model
    attributes:
      label: Raspberry Pi Model
      options:
        - Raspberry Pi 1 B
        - Raspberry Pi 2
        - Raspberry Pi 3
        - Raspberry Pi Zero W
        - Raspberry Pi Zero WH
        - Raspberry Pi Zero 2 W
        - Raspberry Pi 3 A+
        - Raspberry Pi 3 B+
        - Raspberry Pi 4 B
        - Raspberry Pi 5
        - Other (specify in description)
      description: |
        If you are running on a Raspberry Pi, please tell us which model Raspberry Pi you are using.
    validations:
      required: false
