name: Node-CI Alpha

on:
  push:
    branches: [alpha-*.*.*, alpha]
  workflow_dispatch:

jobs:
  publish:
    if: ${{ github.repository == 'homebridge/homebridge-config-ui-x' }}
    uses: homebridge/.github/.github/workflows/npm-publish.yml@latest
    with:
      tag: 'alpha'
      dynamically_adjust_version: true
      npm_version_command: 'pre'
      pre_id: 'alpha'
      install_cmd: npm ci && cd ui && npm ci
    secrets:
      npm_auth_token: ${{ secrets.npm_token }}
