name: Node-CI Beta

on:
  push:
    branches: [beta-*.*.*, beta]
  workflow_dispatch:

jobs:
  build_and_test:
    uses: homebridge/.github/.github/workflows/nodejs-build-and-test.yml@main
    with:
      enable_coverage: true
      install_cmd: npm ci && cd ui && npm ci
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    needs: build_and_test
    uses: homebridge/.github/.github/workflows/eslint.yml@main
    with:
      install_cmd: npm ci && cd ui && npm ci

  publish:
    needs: lint

    if: ${{ github.repository == 'homebridge/homebridge-config-ui-x' }}

    uses: homebridge/.github/.github/workflows/npm-publish.yml@main
    with:
      tag: 'test'
      dynamically_adjust_version: true
      npm_version_command: 'pre'
      pre_id: 'test'
      install_cmd: npm ci && cd ui && npm ci
    secrets:
      npm_auth_token: ${{ secrets.npm_token }}
